config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {

    $routes->extensions( ['json', 'ajax']);
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Properties', 'action' => 'home', 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/Property.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Property Entity
 *
 * @property int $id
 * @property string $type
 * @property string $title
 * @property string $house_no
 * @property string $address
 * @property int $zip_id
 * @property int $status
 * @property string $contact_number
 * @property string $email
 * @property int $room_size
 * @property int $total_size
 * @property string $description
 * @property string $transportation
 * @property bool $direct_bus_to_uni
 * @property string $house_rules
 * @property string $looking_for
 * @property \Cake\I18n\Time $available_from
 * @property \Cake\I18n\Time $available_until
 * @property int $rent
 * @property int $deposit
 * @property int $utility_cost
 * @property int $dist_from_uni
 * @property string $time_dist_from_uni
 * @property bool $smoking
 * @property bool $pets
 * @property bool $handicap
 * @property bool $fire_alarm
 * @property bool $washing_machine
 * @property bool $parking
 * @property bool $heating
 * @property bool $bike_parking
 * @property bool $garden
 * @property bool $balcony
 * @property bool $cable_tv
 * @property bool $electricity_bill_included
 * @property bool $internet
 * @property int $view_times
 * @property int $is_boosted
 * @property \Cake\I18n\Time $created
 * @property \Cake\I18n\Time $modified
 *
 * @property \App\Model\Entity\Zip $zip
 * @property \App\Model\Entity\FavoriteProperty[] $favorite_properties
 * @property \App\Model\Entity\Image[] $images
 * @property \App\Model\Entity\User[] $users
 */
class Property extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false
    ];


    /**
     * Virtual field
     * Return studierent score calculated using other field values
     * @author Touhidur Rahman
     */
     protected function _getStudierentScore() {
         $score = 0;
         // 10 points based on room and flat size, give some points     = 10
         $sizeFactor = $this->_properties['total_size'] / $this->_properties['room_size'] * 100;
         if ($sizeFactor <= 40) {
             $score += 5;
         } else if ($sizeFactor <= 60) {
             $score += 8;
         } else {
             $score += 10;
         }
         // 10 points for these 3                                       = 20
         if ($this->_properties['description'])                     $score += 2;
         if (strlen($this->_properties['description']) > 400)       $score += 2;
         if ($this->_properties['transportation'])                  $score += 2;
         if (strlen($this->_properties['transportation']) > 200)    $score += 1;
         if ($this->_properties['house_rules'])                     $score += 2;
         if (strlen($this->_properties['house_rules']) > 100)       $score += 1;

         // 5 points for looking_for                                    = 25
         switch ($this->_properties['looking_for']) {
             case 'Male':
                 $score += 3;
                 break;

             case 'Female':
                 $score += 3;
                 break;

             default:
                 $score += 5;
                 break;
         }

         // 10 points for availability                                  = 35
         $from = $this->_properties['available_from'];
         $to = $this->_properties['available_until'];
         $availabilityFactor = $from->diffInDays($to);
         if ($availabilityFactor <= 60) {
             $score += 4;
         } else if ($availabilityFactor <= 180) {
             $score += 6;
         } elseif ($availabilityFactor < 365) {
             $score += 8;
         } else {
             $score += 10;
         }

         // 10 points for rent deposit utility_cost                     = 45
         if ($this->_properties['deposit'] < 2 * $this->_properties['rent']) {
             $score += 8;
         } else {
             $score += 4;
         }
         if ($this->_properties['utility_cost'] < ($this->_properties['rent'] / 5)) $score += 2;

        // 15 points for distance                                       = 60
        if ($this->_properties['direct_bus_to_uni']) $score += 5;
        if ($this->_properties['dist_from_uni'] <= 2) {
            $score += 10;
        } else if ($this->_properties['dist_from_uni'] <= 5) {
            $score += 8;
        } else if ($this->_properties['dist_from_uni'] <= 10) {
            $score += 5;
        } else {
            $score += 3;
        }

        // 30 points for amenities                                      = 90
        if ($this->_properties['internet'] == 1)                     $score += 4;
        if ($this->_properties['electricity_bill_included'] == 1)    $score += 4;
        if ($this->_properties['heating'] == 1)                      $score += 4;
        if ($this->_properties['washing_machine'] == 1)              $score += 2;
        if ($this->_properties['parking'] == 1)                      $score += 2;
        if ($this->_properties['bike_parking'] == 1)                 $score += 2;
        if ($this->_properties['fire_alarm'] == 1)                   $score += 2;
        if ($this->_properties['garden'] == 1)                       $score += 2;
        if ($this->_properties['balcony'] == 1)                      $score += 2;
        if ($this->_properties['handicap'] == 1)                     $score += 2;
        if ($this->_properties['cable_tv'] == 1)                     $score += 2;
        if ($this->_properties['smoking'] == 0)                      $score += 2;

        // 10 points for is_boosted                                     = 100
        if ($this->_properties['is_boosted'])                        $score += 10;

        return $score;

     }
}

src/Model/Table/UsersTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Users Model
 *
 * @property \Cake\ORM\Association\BelongsTo $Cities
 * @property \Cake\ORM\Association\HasMany $FavoriteProperties
 * @property \Cake\ORM\Association\HasMany $Feedbacks
 * @property \Cake\ORM\Association\BelongsToMany $Properties
 *
 * @method \App\Model\Entity\User get($primaryKey, $options = [])
 * @method \App\Model\Entity\User newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\User[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\User|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\User patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\User[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\User findOrCreate($search, callable $callback = null)
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class UsersTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('users');
        $this->displayField('username');
        $this->primaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Cities', [
            'foreignKey' => 'city_id'
        ]);
        $this->hasMany('FavoriteProperties', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('Feedbacks', [
            'foreignKey' => 'for_user_id'
        ]);
        $this->hasMany('Properties', [
            'foreignKey' => 'user_id'
        ]);
        // $this->belongsToMany('Properties', [
        //     'foreignKey' => 'user_id',
        //     'targetForeignKey' => 'property_id',
        //     'joinTable' => 'users_properties'
        // ]);
        $this->hasOne('AvgRatings', [
            'foreignKey' => 'user_id',
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->requirePresence('first_name', 'create')
            ->notEmpty('first_name');

        $validator
            ->requirePresence('last_name', 'create')
            ->notEmpty('last_name');

        $validator
            ->requirePresence('username', 'create')
            ->notEmpty('username');

        $validator
            ->requirePresence('password', 'create')
            ->notEmpty('password');

        $validator
            ->requirePresence('gender', 'create')
            ->notEmpty('gender');

        $validator
            ->requirePresence('address', 'create')
            ->notEmpty('address');

        $validator
            ->integer('status')
            ->allowEmpty('status');

        $validator
            ->requirePresence('contact_number')
            ->allowEmpty('contact_number');

        $validator
            ->allowEmpty('photo');

        $validator
            ->allowEmpty('reset_key');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->isUnique(['username']));
        // $rules->add($rules->existsIn(['city_id'], 'Cities'));

        return $rules;
    }
}

src/Template/Properties/_view.bak.ctp
<div class="row">
    <div class="col-xs-12">
        <div class="fill">

        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <?php $i = 0; foreach ($property->images as $img) : ?>

                <div class="carousel-item <?= ($i==0)? 'active' : ''; ?>">
                    <div class="fill">
                        <?= $this->Html->image('properties'.DS.$img->path); ?>
                    </div>
                </div>

                <?php $i++; endforeach; ?>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="icon-prev" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="icon-next" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>

src/Template/Properties/add.ctp
<!-- Add Property -->

<h1 class="display-4">Add a Property Ad</h1>

<?= $this->Form->create($property, ['horizontal' => false]) ?>
<div class="row">
    <div class="col-sm-6">
        <div class="card">
            <div class="card-block">
                <h4 class="card-title">Type & Title</h4>
                <?php  $options = array('Select property type'=>'Select property type','Flat'=>'Flat','Flatshare'=>'Flatshare','Student Residence'=>'Student Residence','House'=>'House'); ?>
                <?= $this->Form->input('type', array('type'=>'select', 'options'=>$options)) ?>
                <?php echo $this->Form->input('title');?>
            </div>
        </div>
    </div>

    <div class="col-sm-6">
        <div class="card">
            <div class="card-block">
                <h4 class="card-title">Address</h4>
                <?php
                echo $this->Form->input('house_no', ['label' => 'House Number']);
                echo $this->Form->input('address', ['label' => 'Street']);
                echo $this->Form->input('zip_id', ['type' => 'hidden', 'value' => $zipid]);
                ?>
            </div>
        </div>
    </div>

    <div class="col-sm-6">
        <div class="card">
            <div class="card-block">
                <h4 class="card-title">Details</h4>
                <?php
                echo $this->Form->input('room_size', ['min' => 0, 'label' => 'Room Size (sq M)']);
                echo $this->Form->input('total_size', ['min' => 0, 'label' => 'Total Size (sq M)']);
                echo $this->Form->input('available_from');
                echo $this->Form->input('available_until'); ?>
                <?php echo $this->Form->input('looking_for', ['type' => 'select', 'options' => ['Any Gender' => 'Any Gender', 'Male' => 'Male', 'Female' => 'Female']]);
                echo $this->Form->input('rent', ['min' => 0, 'label' => 'Rent (Monthly)']);
                echo $this->Form->input('deposit', ['min' => 0, 'label' => 'Initial Deposit (One Time)']);
                echo $this->Form->input('utility_cost', ['min' => 0, 'label' => 'Utilities Cost (Monthly)']);
                ?>
            </div>
        </div>
    </div>

    <div class="col-sm-6">
        <div class="card">
            <div class="card-block">
                <h4 class="card-title">Amenities</h4>
                <?php
                echo $this->Form->input('dist_from_uni', ['label' => 'Distance from University (KM)']);
                echo $this->Form->input('time_dist_from_uni', ['type' => 'number', 'min' => 0, 'max' => 100, 'step' => '5', 'label' => 'Walking Distance From the University (Minutes)', 'placeholder' => '10']);
                echo $this->Form->input('electricity_bill_included', ['label' => 'Electricity Bill Included in Rent']);
                echo $this->Form->input('direct_bus_to_uni', ['label' => 'Direct Bus Route to University']);
                echo $this->Form->input('internet');
                echo $this->Form->input('heating');
                echo $this->Form->input('cable_tv');
                echo $this->Form->input('washing_machine');
                echo $this->Form->input('parking');
                echo $this->Form->input('bike_parking');
                echo $this->Form->input('smoking');
                echo $this->Form->input('pets');
                echo $this->Form->input('handicap');
                echo $this->Form->input('fire_alarm');
                echo $this->Form->input('garden');
                echo $this->Form->input('balcony');
                ?>
            </div>
        </div>
    </div>

    <div class="col-sm-12">
        <div class="card">
            <div class="card-block">
                <?php
                echo $this->Form->input('description');
                echo $this->Form->input('transportation');
                echo $this->Form->input('house_rules');
                ?>
            </div>
        </div>
    </div>

    <div class="col-sm-6">
        <div class="card">
            <div class="card-block">
                <h4 class="card-title">Owner's Contact Information</h4>
                <?php
                echo $this->Form->input('contact_number');
                echo $this->Form->input('email');
                ?>
            </div>
        </div>
    </div>

</div>

<?= $this->Form->button(__('Submit'), ['class' => 'btn btn-success']) ?>
<?= $this->Form->end(); ?>

src/Template/Properties/boost.ctp
<h1 class="display-4" style="text-align:center;">Boost your property for more views!</h1>
<div class="card">
    <div class="card-block">
        <h4 class="card-title"><?= $property['title'] ?></h4>
        <h6 class="card-subtitle text-muted">
            <?= $property['address'] ?>
        </h6>
    </div>
    <?php
    if ($property['images']) {
        echo $this->Html->image('properties'.DS.$property['images'][0]->path, ['alt' => 'Property image', 'class' => 'img-fluid', 'style' => 'width:100%;']);
    } else {
    ?>
        <h1 class="display-1 text-xs-center text-success"><i class="fa fa-home fa-lg"></i></h1>
    <?php
    }
    ?>
    <div class="card-block">
        <p class="text-xs-center text-muted" style="margin-bottom:0">EUR</p>
        <h4 class="display-4 text-xs-center text-warning font-weight-bold"><?= $property['rent']?></h4>
    </div>
</div>
<?php
$boosted = false;
if ($property['is_boosted'] == 1) {
    if($property['boosted_till']) {
        if ($property['boosted_till']->isWithinNext(7)) $boosted = true;
    }
}
?>
<?php if($boosted){  ?>
<h6 style="text-align: center;">
    This add is already boosted
        </h6>
<?php }else{  ?>
<?= $this->Form->create($property)?>
<p>You <?=date('Y-m-d H:i:s');?> can boost your ad with only 2 EUR for 7 days. If you click the "Boost" button, it will take you to the third party payment site, where you can pay through Credit card.</p>
<div class="form-group row" style="text-align: center;" >
    <input type="hidden" name="is_boosted" value="1"/>
    <?= $this->Form->button(__('Boost'), ['class' => 'btn btn-success']) ?>
    </div>
    <?= $this->Form->end(); ?>
<?php }?>

src/Template/Properties/favorites.ctp
<h1 class="display-4">Favorite Properties</h1>

<?php if ($id_exists) { ?>
<?php foreach ($properties as $property) {
    echo $this->element('adSnippet', ['property' => $property, 'avgRatings' => $avgRatings]);
} ?>

<!-- Pagination -->
<div class="text-xs-center">
    <?php echo $this->Paginator->prev('<<'); ?>
    <?php echo $this->Paginator->numbers(); ?>
    <?php echo $this->Paginator->next('>>'); ?>
</div>
<?php } ?>
<?php if (!$id_exists) { ?>
<h2>Sorry, you have no favorite properties </h2>
<?php } ?>

src/Template/Properties/myproperties.ctp
<h1 class="display-4">My Properties</h1>
<?php foreach ($properties as $property){
    echo $this->element('adSnippetLandlord', ['property' => $property]);

} ?>
<div class="text-xs-center">
    <?php echo $this->Paginator->prev('<<'); ?>
    <?php echo $this->Paginator->numbers(); ?>
    <?php echo $this->Paginator->next('>>'); ?>
</div>

src/Template/Properties/view.ctp
<div class="row">
	<div class="col-xs-8">

		<div class="card">
			<div class="card-header">
				<i class="fa fa-image"></i> Images
			</div>
			<div class="card-block text-xs-center">
				<?php $i = 0; foreach ($property->images as $img) : ?>
					<a class="" data-lightbox="sample" href="/img/properties/<?= $img->path ?>">
						<?= $this->Html->image('properties'.DS.$img->path, ['class' => 'card-img', 'width' => '240', 'height' => '180', 'style' => 'padding:.5rem']); ?>
					</a>
					<?php $i++; endforeach; ?>
				</div>
			</div>

			<script>
			lightbox.option({
				'resizeDuration': 200,
				'wrapAround': true,
				'fitImagesInViewport': true,
				'maxWidth': 1200,
				'maxHeight': 900
			})
			</script>

			<?php $boosted = (($property['is_boosted'] == 1) && ($property['boosted_till']->isWithinNext(7))) ? true : false; ?>

			<div class="card">
				<div class="card-header">
					<h3 class="text-success">
						<?= ($boosted)? '<i class="fa fa-diamond fa-lg text-warning"></i>' : '' ?>
						<?= $property->title ?>
					</h3>
				</div>

				<div class="card-block">
					<div class="card-title">
						<h4 class="">Amenities</h4>
					</div>
					<table class="table table-sm table-fluid">
						<?php $check = '<i class="fa fa-check text-success"></i>'; $times = '<i class="fa fa-times text-danger"></i>'; ?>
						<tr>
							<td><?php echo ($property->electricity_bill_included == 1) ? $check : $times; ?> Electricity Bill Included</td>
							<td><?php echo ($property->heating == 1) ? $check : $times; ?> Heating</td>
						</tr>
						<tr><td><?php echo ($property->internet == 1) ? $check : $times; ?> Internet</td>
							<td><?php echo ($property->washing_machine == 1) ? $check : $times; ?> Washing Machine</td>
						</tr>
						<tr>
							<td><?php echo ($property->fire_alarm == 1) ? $check : $times; ?> Fire Alarm</td>
							<td><?php echo ($property->bike_parking == 1) ? $check : $times; ?> Bike Parking</td>
						</tr>
						<tr>
							<td><?php echo ($property->parking == 1) ? $check : $times; ?> Parking</td>
							<td><?php echo ($property->balkony == 1) ? $check : $times; ?> Balkony</td>
						</tr>
						<tr>
							<td><?php echo ($property->handicap == 1) ? $check : $times ?> Handicap Friendly</td>
							<td><?php echo ($property->garden == 1) ? $check : $times; ?> Garden</td>
						</tr>
						<tr>
							<td><?php echo ($property->cable_tv == 1) ? $check : $times; ?> Cable TV</td>
							<td><?php echo ($property->phone == 1) ? $check : $times; ?> Phone</td>
						</tr>
						<tr>
							<td><?php echo ($property->cable_tv == 1) ? $check : $times; ?> Smoking</td>
							<td><?php echo ($property->pets == 1) ?$check : $times; ?> Pets</td>
						</tr>
					</table>
				</div>
				<div class="card-block">
					<h4>Description</h4>
					<p class="text-justify"><?= h($property->description) ?></p>
				</div>
				<div class="card-block">
					<h4>Transportation</h4>
					<p><?php echo ($property->direct_bus_to_uni == 1) ? $check : $times; ?>  Direct bus to University</p>
					<p class="text-success"><?php echo $property->dist_from_uni; ?>  KM Far from University / <?php echo $property->time_dist_from_uni; ?> Minutes by Walking (Approximate Estimation)</p>
					<p class="text-justify"><?= h($property->transportation) ?></p>
				</div>
				<div class="card-block">
					<h4>House Rules</h4>
					<p class="text-justify"><?= h($property->house_rules) ?></p>
				</div>

			</div>
		</div>






		<div class="col-xs-4">
			<div class="card">
				<div class="card-header">
					<i class="fa fa-home"></i> Basic Info
				</div>
				<table class="table table-hover">
					<thead>
						<tr>
							<th colspan="2" class="text-xs-center">
								<label>Monthly Total Rent (EUR)</label>
								<h4 class="display-4 text-warning"><?= $property->rent + $property->utility_cost ?></h4>
								<label class="text-muted">Rent: <?= $property->rent ?> EUR + Utilities: <?= $property->utility_cost ?> EUR</label><br>
								<label class="text-primary">Deposit: <?= $property->deposit ?> EUR</label>
							</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td class="text-success">Studierent Score <i class="fa fa-bolt"></i></td>
							<td class="text-success"><?= $property->studierent_score ?> (Out of 100)</td>
						</tr>
						<tr>
							<td>Room Size</td>
							<td><?= $property->room_size ?> M<sup>2</sup></td>
						</tr>
						<tr>
							<td>Total Flat/House Size</td>
							<td><?= $property->total_size ?> M<sup>2</sup></td>
						</tr>
						<tr>
							<td>Looking For</td>
							<td><?= $property->looking_for ?></td>
						</tr>
						<tr>
							<td>Available From</td>
							<td><?= $property->available_from ?></td>
						</tr>
						<tr>
							<td>Available To</td>
							<td><?= $property->available_until ?></td>
						</tr>
						<tr>
							<td>Address</td>
							<td><?php echo $property->address .' '. $property->house_no .',<br> '. $property->zip->number .' '. $property->zip->city; ?></td>
						</tr>
						<tr>
							<td class="text-danger">Favorite? <?= $this->Html->link('<i class="fa fa-heart-o"></i>', '/properties/toggleFavorites.json?id='.$property['id'], ['class' => 'card-link text-danger favTogglers', 'escapeTitle' => false, 'title' => 'Click to add/remove this property ad to/from your favorites!']) ?></td>
							<td>Report? <?= $this->Html->link('<i class="fa fa-flag-o"></i>', '/reports/add/'.$property['id'], ['class' => 'card-link text-muted', 'escapeTitle' => false, 'title' => 'Report this Ad! Help us improve Studierent by filtering abuses.']) ?></td>
						</tr>
					</tbody>
				</table>
			</div>

			<div class="card">
				<div class="card-header">
					<i class="fa fa-user"></i> Landlord Info
				</div>

				<table class="table">
					<tbody>
						<tr>
							<th>Name</th>
							<td><?= $property->user->first_name . ' ' . $property->user->last_name ?></td>
						</tr>
						<tr>
							<th>Contact Number</th>
							<td><?= $property->contact_number ?></td>
						</tr>
						<tr>
							<th>Email</th>
							<td><?= $property->email ?></td>
						</tr>
						<tr>
							<th>Rating: </th>
							<td>
								<?php
								$avgRatingCount = 0;
								foreach ($avgRating as $avg) {
									$avgRatingCount = $avg->avg_rate;
									if ($avg->user_id == $property['user_id']) {
										if( $avg->avg_rate==0){ ?>
											<p>Not Rated yet</p>
											<?php
										} else {
											$filledStar = ceil($avg->avg_rate);
											$hollowStar = 5 - $filledStar;
											for ($i=0; $i < $filledStar; $i++) {
												echo '<i class="fa fa-star text-info"></i>';
											}
											for ($i=0; $i < $hollowStar; $i++) {
												echo '<i class="fa fa-star-o text-info"></i>';
											}
										}
									}
								}
								?>
							</td>
						</tr>
					</tbody>
				</table>

				<div class="card-block">
					<p class="text-success">Recent Reviews:</p>
					<blockquote class="card-blockquote">
						<?php if( $avgRatingCount==0){ ?>
							<p>No Review So Far</p>
							<?php }else{  ?>
								<p> <?php echo $feedback->text; ?></p>

								<?php  }?>

							</blockquote>
						</div>
						<div class="card-block">
							<?= $this->Html->link('Landlord Profile', '/users/view/'.$property->user->id, ['class' => 'btn btn-success']) ?>
							<?= $this->Html->link('Submit Review', '/users/view/'.$property->user->id, ['class' => 'btn btn-warning']) ?>
						</div>
					</div>
				</div>


			</div>